{% set version = '9.1.0' %}

package:
  name: gcc-{{ environ.get('TOOLCHAIN_ARCH') }}-linux-musl
  version: {{ version }}

source:
  - url: https://ftp.gnu.org/gnu/binutils/binutils-2.32.tar.xz
    fn: binutils-2.32.tar.bz2
    sha256: 0ab6c55dd86a92ed561972ba15b9b70a8b9f75557f896446c82e8b36e473ee04
    folder: binutils
  - git_url: https://github.com/mithro/kernel-headers.git
    git_rev: master
    folder: kernel-headers
  - url: http://ftp.gnu.org/gnu/gcc/gcc-{{ version }}/gcc-{{ version }}.tar.xz
    fn: gcc-{{ version }}.tar.gz
    sha256: 79a66834e96a6050d8fe78db2c3b32fb285b230b855d0a66288235bc04b327a0
    folder: gcc
  - git_url: git://git.musl-libc.org/musl
    git_rev: ac304227bb3ea1787d581f17d76a5f5f3abff51f
    folder: musl
{% if environ.get('TOOLCHAIN_ARCH') == 'riscv32' %}
    patches:
     - 0001-20190519-merge-riscv.patch
{% endif %}

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS
    - TOOLCHAIN_ARCH
  detect_binary_files_with_prefix: False
  binary_relocation:
    - 'bin/*'
    - 'lib/*.so*'
    - 'libexec/**/*.so*'
    - 'libexec/**/cc1*'
    - 'libexec/**/collect2'
    - 'libexec/**/gcc'
    - 'libexec/**/lto*'
    - 'libexec/**/plugin/gengtype'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # These are taken from the output of the configure scripts
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl >=0.15.0
    - cloog
  run:
    - isl
    - mpc

about:
  home: https://gcc.gnu.org/
  license: GPL
  summary: 'The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Java, Ada, and Go, as well as libraries for these languages (libstdc++, libgcj,...).'
