ctng_sample:
  - or1k-multilib-elf
ctng_target_platform:
  - or1k
ctng_gcc:
  - 8.2.0
ctng_langs:
  - c,c++
ctng_libc:
  - newlib
ctng_newlib:
  - 3.0.0.20180226
#ctng_nature:
#  - static
#ctng_gdb:
#  - 8.1
