ctng_sample:
  - lm32-multilib-elf
ctng_target_platform:
  - lm32
ctng_gcc:
  - 8.2.0
ctng_langs:
  - c
ctng_libc:
  - newlib
ctng_newlib:
  - 3.0.0.20180226
#ctng_nature:
#  - static
#ctng_gdb:
#  - 8.1
ctng_duma: no
